---
title: "Total Pages in the Code of Federal Regulations"
author: "Yaxin Zhuang"
date: "`r Sys.Date()`"
output: html_document
---

## Initialize

The `i_am` function identifies where the Rmd is located within the main project directory. All future calls to files are based on their relative location to the project root.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/cfr_pages.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "cfr_pages_by_calendar_year.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

## Load Packages

```{r imports, results='hide', warning=FALSE}

library(ggplot2)
library(showtext)
library(png)
library(ggpattern)
library(tidyr)
library(ggrepel)
library(dplyr)
library(scales)
library(gcookbook)
```

## Load data

```{r load_data}

# load csv using here
df <- read.csv(here("charts", "data", data_file))



#load custom font
font_add("avenir_lt_pro","a-avenir-next-lt-pro.otf")
showtext_auto()
```

## Process data

```{r clean_data}


df1 <- df[c(16:87),c(0:3)]
colnames(df1) <- c("year", "color", "tolpages")

current_date <- format(Sys.Date(), "%B %d, %Y")
caption_text <- paste("Source: Office of the Federal Register (federalregister.gov) for the years starting 2021;\n       Office of Information and Regulatory Affairs (OIRA) (reginfo.gov) for all prior years.\n\nUpdated:", current_date)

df2 = subset(df1, select = -c(color) )

df2$tolpages <- as.numeric(gsub(",","",df2$tolpages))
df2$year <- as.numeric(df2$year)

```

## Plot data

```{r plot_data, results='markup'}
# create caption text
caption_text <- paste("Sources:  Federal Register Statistics \n\nUpdated:", current_date)

# format wrapping setting for caption text
wrapped_caption <- paste(strwrap(caption_text, width = 75), collapse = "\n")

upper <- ydynam(df2, 20000, 2)

breaks4 <- c(seq(min(df2$year), max(df2$year), 4), 2021)

bar2 <-
  ggplot(data=df2, aes(x=year, y=tolpages)) +
  geom_bar(stat="identity", fill="#033C5A")+
  #geom_text(aes(label=len), vjust=-0.3, size=3.5)+

  ggtitle("Total Pages Published in the Code of Federal Regulations") +
  ylab("Thousands of Pages") +
  xlab("") +
  scale_y_continuous(breaks = seq(0, upper, by = 20000), expand = c(0, 0),
                     limits = c(-2, upper),
                     #labels = function(x) ifelse(x == 0, "0", scales::label_number(suffix = "K", scale = 1e-3)(x)),) +
                     labels = function(x) ifelse(x == 0, "0", scales::label_number( scale = 1e-3)(x)),) +

    scale_x_continuous(breaks = breaks4,
                     limits = c(min(df2$year)-1, max(df2$year)+1),
                     expand = c(0,0)) + 
  coord_cartesian(clip = "off") +
  #theme_RSC +
  labs(caption = wrapped_caption)+
  theme_minimal() +
  theme(
      plot.title = element_text(hjust = 0.5, vjust = 0, margin = margin(b = 10, unit = "pt"), size = 20),
      legend.position = "none",
      panel.grid.major.x = element_blank(),
      axis.text.x = element_text(angle = 65, hjust = 1, vjust = 1, size = 12),
      axis.title.x = element_text(size = 12, angle = 0, vjust = 0.5, hjust = 0.5, margin = margin(t = 20)),
      #axis.ticks.x = element_line(color = RSCgray),
      axis.text.y = element_text(size = 12),
      axis.line.x = element_line(linewidth = 1, color = RSCgray),

      axis.title.y = element_text(size = 12, angle = 90, vjust = 0.5, hjust = 0.5, margin = margin(r = 20)),# modified margin to adjust the space between title and y-axis 
      panel.grid.major.y = element_line(color = RSCgray, linetype = "solid", linewidth = 0.50),
      panel.grid.minor = element_blank(),
      text = element_text(family = "avenir_lt_pro"),
      plot.caption = element_text(hjust = 1, vjust = 0, margin = margin(t = 10, l = 6, unit = "pt"), size = 11),
      plot.margin = margin(50, 50, 50, 50)
    )


#logo 
new_bar <- ggdraw() +
      draw_plot(bar2) +
      draw_image(logo, x = 0.1, y = 0.05, halign = 0, valign = 0, width = 0.2)

new_bar

```

```{r save}
# create empty output folder if it doesn't already exist
out = here("charts", "output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}

# save as pdf
ggsave(here("charts", "output", "cfr_pages_by_calendar_year.pdf"), plot = new_bar, width = 12, height = 9, dpi = 300)
```
