---
title: "Cumulative Economically Significant Final Rules by Administration"
author: "Henry Hirsch"
date: "2023-10-26"
output: html_document
---

```{r clear environment}
# clear environment
rm(list=ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
here::i_am("charts/code/cum_sig_rules.Rmd")
```

```{r load packages, results='hide', warning=FALSE}
# load packages
library(tidyverse)
library(ggrepel)
library(png)
library(here)
source(here("charts", "code", "local_utils.R"))
```

```{r load style, message=FALSE}
# load style
source(here("charts", "code", "style.R"))
```

```{r load data}
# load csv using here
cum_sig <- read.csv(here("charts", "data", "cumulative_econ_significant_rules_by_presidential_month.csv"), skip = 1)

# eventually separate this into another file for reuse, then import/call the function
# ^ HOW TO DO THIS?
# get_png <- function(filename) {
#   grid::rasterGrob(png::readPNG(filename),interpolate = TRUE)
# }

l <- get_png(here("charts", "style", "gw_ci_rsc_2cs_pos.png"))

```

```{r clean data and update president names}
# Create president_names list which can be updated at the top of the code and then referenced later in the code as needed?

# rename columns (will need to manually update with the names of new presidents)
colnames(cum_sig) <- c("month", "months_in_office", "Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden")

# get rid of unnecessary columns (will also need to manually update with new president names here)
cum_sig <- cum_sig[ , c("months_in_office", "Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden")]

# get rid of unnecessary rows (this would need to be altered if a president served more than two terms)
cum_sig <- cum_sig[-c(98:101), ]

# create long data frame (will also need to manually add new president's names here)
cum_sig_long_NA <- pivot_longer(cum_sig, cols = c("Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden"), names_to = "president", values_to = "econ_rules")

# remove NA values from long data frame (these NA values are the potential econ_rules values for presidents who didn't/haven't yet served the maximum number of months)
cum_sig_long <- cum_sig_long_NA[complete.cases(cum_sig_long_NA), ]

# change president column to factor (assign levels and labels)
cum_sig_long <- cum_sig_long %>% 
  mutate(president = factor(president,
                        levels = c("Reagan", 
                                   "Bush_41",
                                   "Clinton", 
                                   "Bush_43",
                                   "Obama", 
                                   "Trump",
                                   "Biden"),
                        labels = c("Reagan", 
                                   "Bush 41",
                                   "Clinton", 
                                   "Bush 43",
                                   "Obama", 
                                   "Trump",
                                   "Biden")))

# create list of colors for presidents (to be updated)?
```

```{r endpoints/date/caption}
# calculate the end points of the lines
line_ends <- cum_sig_long %>%
  group_by(president) %>%
  summarise(months_in_office_end = max(months_in_office), econ_rules_end = max(econ_rules))

# set current date
current_date <- format(Sys.Date(), "%B %d, %Y")

# set caption text
caption_text <- paste("Sources: Office of the Federal Register (federalregister.gov) for Biden administration and all subsequent administrations;\n       Office of Information and Regulatory Affairs (OIRA) (reginfo.gov) for all prior administrations.\n\nUpdated:", current_date)
```


```{r generate graph}
# generate line graph
line1 <- ggplot(cum_sig_long, aes(x = months_in_office, y = econ_rules, color = president, group = president)) + 
  geom_line(linewidth = 0.75) +
  geom_label_repel(data = line_ends, 
                  aes(x = months_in_office_end, y = econ_rules_end, label = president),
                  nudge_x = 0, nudge_y = 10,
                  segment.size = 0.2,
                  size = 3,
                  point.size = 1,
                  box.padding = 0,
                  point.padding = 0,
                  min.segment.length = 0.9,
                  force = 3,
                  label.size = NA, 
                  label.padding = 0,
                  label.r = 0,
                  fill = alpha(c("white"), 0.8)) +
  scale_color_manual(values = c(red,
                                darkgreen,
                                GWblue,
                                GWbuff,
                                lightblue,
                                darkyellow,
                                lightgreen)) +
  annotation_custom(l, xmin = 0, xmax = 18, ymin = -100, ymax = -45) + # for logo (need to play around with these settings)
  coord_cartesian(clip = "off") +
  theme_minimal() +
  theme_RSC +
  # theme(plot.title = element_text(hjust = 0.5),
  #       legend.position = "none",
  #       panel.grid.major.x = element_blank(),
  #       panel.grid.major.y = element_line(color = "lightgray", linetype = "solid"),
  #       panel.grid.minor = element_blank(), 
        #plot.caption = element_text(hjust = 1, margin = margin(t = 10, l = 6, unit = "pt")),
        #axis.ticks.x = element_line(color = "lightgrey"),
        #axis.title.x = element_text(margin = margin(t = 10), hjust = 0.5),
        #axis.title.y = element_text(margin = margin(r = 10), vjust = 0.5),
        #axis.text.x = element_text(angle = 0),
        #plot.margin = margin(40, 40, 40, 40)
        #) +
  xlab("Number of Months In Office") +
  ylab("Number of Economically Significant Rules Published") +
  ggtitle("Cumulative Economically Significant Final Rules by Administration") +
  labs(color = "President", caption = caption_text) +
  scale_y_continuous(breaks = seq(0, max(cum_sig_long$econ_rules) + 50, by = 50),
                     expand = c(0, 0), 
                     limits = c(-2, max(cum_sig_long$econ_rules) + 50)) +
  scale_x_continuous(breaks = seq(0, max(cum_sig_long$months_in_office), by = 4),
                     expand = c(0, 0),
                     limits = c(0, max(cum_sig_long$months_in_office)))

line1
```

```{r output folder}
# create empty output folder if it doesn't already exist
out = here("output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}
```

```{r save to output}
# save line1 as pdf
ggsave(here("output", "Cumulative Economically Significant Final Rules by Administration.pdf"), plot = line1, width = 12, height = 9, dpi = 300)
```

