---
title: "Cumulative Economically Significant Final Rules by Administration in first year"
author: "Yaxin Zhuang"
date: "`r Sys.Date()`"
output: html_document
---

## Initialize

The `i_am` function identifies where the Rmd is located within the main project directory. All future calls to files are based on their relative location to the project root.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/cumulative_econ_significant_rules_first_year.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "cumulative_econ_significant_rules_by_presidential_month.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

## Load Packages

```{r imports, results='hide', warning=FALSE}

library(ggplot2)
library(ggpattern)
library(ggrepel)
library(dplyr)

```

## Load data

```{r load_data}

# load csv using here
cun_sig_first <- read.csv(here("charts", "data", data_file))
#load custom font

font_add("avenir_lt_pro","a-avenir-next-lt-pro.otf")
showtext_auto()


```

## Process data

```{r clean_data}

cum_sig <- cun_sig_first[c(2:13), ]

# rename columns (will need to manually update with the names of new presidents)
colnames(cum_sig) <- c("month", "months_in_office", "Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden")

# get rid of unnecessary columns (will also need to manually update with new president names here)
cum_sig <- cum_sig[ , c("months_in_office", "Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden")]

# get rid of unnecessary rows (this would need to be altered if a president served more than two terms)
cum_sig <- cum_sig[-c(98:101), ]

# create long data frame (will also need to manually add new president's names here)
cum_sig_long_NA <- pivot_longer(cum_sig, cols = c("Reagan", "Bush_41", "Clinton", "Bush_43", "Obama", "Trump", "Biden"), names_to = "president", values_to = "econ_rules")

# remove NA values from long data frame (these NA values are the potential econ_rules values for presidents who didn't/haven't yet served the maximum number of months)
cum_sig_long <- cum_sig_long_NA[complete.cases(cum_sig_long_NA), ]

# change president column to factor (assign levels and labels)
cum_sig_long <- cum_sig_long %>% 
  mutate(president = factor(president,
                        levels = c("Reagan", 
                                   "Bush_41",
                                   "Clinton", 
                                   "Bush_43",
                                   "Obama", 
                                   "Trump",
                                   "Biden"),
                        labels = c("Reagan", 
                                   "Bush 41",
                                   "Clinton", 
                                   "Bush 43",
                                   "Obama", 
                                   "Trump",
                                   "Biden")))



cum_sig_long$econ_rules <- as.numeric(cum_sig_long$econ_rules)
cum_sig_long$months_in_office <- as.numeric(cum_sig_long$months_in_office)
```

## Plot data

```{r plot_data, results='markup'}



# calculate the end points of the lines
line_ends <- cum_sig_long %>%
  group_by(president) %>%
  summarise(months_in_office_end = max(months_in_office), econ_rules_end = max(econ_rules))

#annotation
current_date <- format(Sys.Date(), "%B %d, %Y")
caption_text <- paste("Source: Office of the Federal Register (federalregister.gov) for Biden administration and all subsequent administrations;\n       Office of Information and Regulatory Affairs (reginfo.gov) for all prior administrations.\n\nUpdated:", current_date)

wrapped_caption <- paste(strwrap(caption_text, width = 75), collapse = "\n")

# generate line graph
line1 <- ggplot(cum_sig_long, aes(x = months_in_office, y = econ_rules, color = president, group = president)) +
         annotate(geom = "segment", x = 48, xend = 48, y = 0, yend = max(cum_sig_long$econ_rules) + 10, linetype = "dashed", linewidth = 0.50, color = RSCgray) +
         annotate(geom = "segment", x = min(cum_sig_long$months_in_office), xend = max(cum_sig_long$months_in_office), y = 0, yend = 0, linetype = "solid", linewidth = 1, color = RSCgray) +  
         geom_line(linewidth = 0.75) +
         geom_label_repel(data = line_ends,
                  aes(x = months_in_office_end, y = econ_rules_end, label = president, family = "avenir_lt_pro"),
                  nudge_x = 0, nudge_y = 2,
                  segment.size = 0.2,
                  segment.color = NA,
                  size = 4,
                  point.size = 1,
                  box.padding = 0,
                  point.padding = 0,
                  min.segment.length = 1,
                  force = 1,
                  label.size = NA,
                  label.padding = 0,
                  label.r = 0,
                  fill = alpha(c("white"), 0.8)) +
  scale_color_manual(values = c(red,
                                darkgreen,
                                GWblue,
                                GWbuff,
                                lightblue,
                                darkyellow,
                                lightgreen)) +
  coord_cartesian(ylim = c(0, max(cun_sig_first_long$econ_rules) + 25)) +
  theme_RSC +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5),
       
) +


  xlab("Number of Months In Office \n\n") +
  #ylab("Number of Economically Significant Rules Published \n\n") +
  ylab("Number of Rules \n\n") +
  ggtitle("Cumulative Economically Significant Final Rules \nby Administration in First Year") +
  labs(color = "President", caption = wrapped_caption) +
  scale_y_continuous(breaks = seq(0, max(cun_sig_first_long$econ_rules) + 25, by = 25),
                     expand = c(0, 0),
                     limits = c(-2, max(cun_sig_first_long$econ_rules) + 25)) +
  scale_x_continuous(breaks = seq(0, max(cun_sig_first_long$months_in_office), by = 4),
                     expand = c(0, 0),
                     limits = c(0, max(cun_sig_first_long$months_in_office)))



```


```{r}
new_bar <- ggdraw() +
      draw_plot(line1) +
      draw_image(logo, x = 0.13, y = 0.076, halign = 0, valign = 0, width = 0.2)

new_bar
```

```{r save}
# create empty output folder if it doesn't already exist
out = here("charts", "output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}

# save line1 as pdf
ggsave(here("charts", "output", "cumulative_econ_significant_rules_by_first_year.pdf"), plot = new_bar, width = 12, height = 9, dpi = 300)
```
