---
title: "Total Pages Published in the Federal Register"
author: "Henry Hirsch"
date: "2023-11-2"
output: html_document
---

## Initialize

The `i_am` function identifies where the Rmd is located within the main project directory. All future calls to files are based on their relative location to the project root.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/federal_register_pages.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "federal_register_pages_by_calendar_year.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

## Load Packages

```{r load packages, results='hide', warning=FALSE}

library(ggplot2)
library(grid)

```

<<<<<<< Updated upstream
## Load Data
=======
```{r load style, message=FALSE}
# load style
source(here("charts/code", "style.R"))
```
>>>>>>> Stashed changes

```{r load data}
# load csv using here
tot_pages <- read.csv(here("charts/data", data_file), skip = 4)

<<<<<<< Updated upstream
logo <- get_png(here("charts", "style", "logo.png"))
=======
# eventually separate this into another file for reuse, then import/call the function
# ^ HOW TO DO THIS?
get_png <- function(filename) {
  grid::rasterGrob(png::readPNG(filename),interpolate = TRUE)
}
>>>>>>> Stashed changes

```

# Process Data

```{r code}
# current date
current_date <- format(Sys.Date(), "%B %d, %Y")

# create caption text
caption_text <- paste("Source: Federal Register Statistics\n\nUpdated:", current_date)

# get rid of bottom 11 rows
tot_pages <- tot_pages[1:(nrow(tot_pages) - 11), ]

# remove blank first row
tot_pages <- tot_pages[-c(1), ]

# remove all columns except for Year and TOTAL
tot_pages <- tot_pages[, c("Year", "TOTAL")]

# change column names
colnames(tot_pages) <- c("year", "total")

# make total an integer variable (remove commas and then convert)
tot_pages$total <- as.integer(gsub(",", "", tot_pages$total))


```

# Plot Data

```{r generate graph}
# generate bar1
bar1 <- ggplot(tot_pages, aes(x = year, y = total)) +
  geom_bar(stat = "identity", fill = GWblue) +
  theme_minimal() +
  theme_RSC +
  ggtitle("Total Pages Published in the Federal Register") +
  ylab("Number of Pages") +
  xlab("") +
  scale_y_continuous(breaks = seq(0, max(tot_pages$total) + 10000, by = 10000), expand = c(0, 0),
                     limits = c(0, max(tot_pages$total) + 10000),
                     labels = function(x) ifelse(x == 0, "0", scales::label_number(suffix = "k", scale = 1e-3)(x))
  ) +
  scale_x_discrete(breaks = seq(min(tot_pages$year), max(tot_pages$year), by = 2)) + 
  labs(caption = caption_text) +
<<<<<<< Updated upstream
  annotation_custom(logo, xmin = -212, xmax = 230, ymin = -19000, ymax = -7000) + # for logo
=======
  # annotation_custom(logo, xmin = -212, xmax = 230, ymin = -19000, ymax = -7000) + # for logo
>>>>>>> Stashed changes
  coord_cartesian(clip = "off") +
  theme_RSC

bar1
```

```{r save}
# create empty output folder if it doesn't already exist
<<<<<<< Updated upstream
out = here("charts", "output")
=======
out = here("charts/output")
>>>>>>> Stashed changes
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}

# save line1 as pdf
<<<<<<< Updated upstream
ggsave(here("charts", "output", "federal_register_pages_by_calendar_year.pdf"), plot = bar1, width = 12, height = 9, dpi = 300)
=======
ggsave(here("charts/output", "Total Pages Published in the Federal Register.pdf"), plot = bar1, width = 12, height = 9, dpi = 300)
>>>>>>> Stashed changes
```

