---
title: "Monthly Economically Significant Rules by Presidential Month"
author: "Deven Patel"
date: "2024-05-15"
output: html_document
---

## Initialize

The `i_am` function identifies where the Rmd is located within the main project directory. All future calls to files are based on their relative location to the project root.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/monthly_econ_significant_rules_by_presidential_month.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "monthly_econ_significant_rules_by_presidential_month.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

# Read data

```{r}
monthly_es0 <- read.csv(here("charts","data", data_file))
```

# Clean data
```{r}
monthly_es1 <- monthly_es0 %>% 
  add_row(Month = "Jan", Months.in.Office = 0, Reagan = 0, Bush.41 = 0, 
          Clinton = 0, Bush.43 = 0, Obama = 0, Trump = 0, Biden = 0)

# create term start dates Month Year
president <- c("Reagan", "Bush.41", "Clinton", "Bush.43", "Obama", "Trump", "Biden")
month <- c("1981-01-01", "1989-01-01", "1993-01-01", "2001-01-01", 
           "2009-01-01", "2017-01-01","2021-01-01")

start0 <- data.frame(president, month) %>% 
  mutate(Month = "Jan") %>% 
  mutate(month = as.Date(month)) %>% 
  mutate(Months.in.Office = 0)

st <- as.Date("1981-02-01")
en <- as.Date("2024-08-01")

monthly_es2 <- pivot_longer(monthly_es1,
                            cols = Reagan:Biden,
                            names_to = "president",
                            values_to = "rules"
                            ) %>% 
  group_by(president) %>% 
  arrange(president, Months.in.Office)

monthly_es3 <- left_join(monthly_es2, start0, by = c("Month", "Months.in.Office", "president"))

monthly_es4 <- monthly_es3 %>% 
  group_by(president) %>% 
  fill(month, .direction = c("down")) %>% 
  arrange(month) %>% 
  ungroup() %>% 
  filter(!is.na(rules),
         Months.in.Office != 0) %>% 
  mutate(date = seq.Date(st, en, by = "1 month"))

start1 <- start0 %>% 
  mutate(rules = 0,
         date = month) %>% 
  select(Month, Months.in.Office, president, rules, month, date)

monthly_es5 <- rbind(monthly_es4, start1) %>% 
  arrange(date) %>% 
  select( -Month, -month) %>% 
  mutate(date = as.Date(date))

```

# Plotting
```{r}
# current date
current_date <- format(Sys.Date(), "%B %d, %Y")

# set caption text
caption_text <- paste("Source: Office of the Federal Register (federalregister.gov)\n\nUpdated", current_date)

# set wrapped caption width
wrapped_caption <- paste(strwrap(caption_text, width = 65), collapse = "\n")

# filter to Biden Admin
to_chart <- monthly_es5 %>% filter(president == "Biden",
                                   Months.in.Office != 0)
bar1 <- ggplot(to_chart,aes(x = date, y = rules)) + 
  geom_bar(stat = "identity", fill = GWblue) +
  ggtitle("Economically Significant Final Rules Published Each Month \n under the Biden Administration") +
  ylab("Number of Rules") +
  xlab("") + 
  scale_y_continuous(breaks = seq(0, ydynam(to_chart, 5, 3), by = 5), 
                     expand = c(0, 0.0),
                     limits = c(0, ydynam(to_chart, 5, 3))) +
  scale_x_date(date_labels = "%b %Y", expand = c(0.01,0.01),
               breaks = seq(from = min(to_chart$date), to = max(to_chart$date), by = "3 months")) +
  labs(caption = wrapped_caption) +
  theme(plot.caption = element_text(hjust = 1, margin = margin(t = 0, l = 36, b = 50, unit = "pt"))) +
  theme_RSC +
  theme(
    plot.title = element_text(hjust = 0.5, margin = margin(b = 20, unit = "pt")),
    axis.text.x = element_text(angle = 65, hjust = 1, vjust = 1),
    axis.ticks.x = element_blank(),
    axis.line.x = element_line(linewidth = 1, color = RSCgray),
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(color = RSCgray, linetype = "solid"),
    panel.grid.minor = element_blank()
  )

suppressWarnings({bar2 <- ggdraw() +
      draw_plot(bar1) +
      draw_image(logo, x = 0.085, y = 0.03, halign = 0, valign = 0, width = 0.2)
bar2})

```
```{r}
# Save pdf and png
out = here("charts", "output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}

image_name = "monthly_econ_significant_rules_by_presidential_month_biden"

ggsave(here("charts", "output", paste0(image_name, ".pdf")), plot = bar2, width = 12, height = 9, dpi = 300)

ggsave(here("charts", "output", paste0(image_name, ".png")), device = "png", plot = bar2, width = 1200, height = 900, units = "px", dpi = 96, bg = "white")

```

