---
title: "Rules Published in the Federal Register by Presidential Year"
author: "Henry Hirsch"
date: "2023-11-2"
output: html_document
---

```{r clear environment}
# clear environment
rm(list=ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/rules_pub_in_FR_by_pres_year.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "federal_register_rules_by_presidential_year.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

```{r load packages, results='hide', warning=FALSE}
# load packages
library(tidyverse)
library(png)
library(here)
```

```{r load style, message=FALSE}
# load style
source(here("code", "style.R"))
```

```{r load data}
# load csv using here
rules_pub_NA <- read.csv(here("data", data_file))

# eventually separate this into another file for reuse, then import/call the function
# ^ HOW TO DO THIS?
get_png <- function(filename) {
  grid::rasterGrob(png::readPNG(filename),interpolate = TRUE)
}

l <- get_png(here("code", "RSC_logo.png"))

```

```{r code}
# modify column names
colnames(rules_pub_NA) <- c("year", "final", "proposed")

# remove rows with NA values
rules_pub <- rules_pub_NA[complete.cases(rules_pub_NA), ]

# make long data frame
rules_pub_long <- pivot_longer(rules_pub, cols = c("final", "proposed"), names_to =
"rule_type", values_to = "rule_num")

# change rule_type column to factor (assign levels and labels)
rules_pub_long <- rules_pub_long %>% 
  mutate(rule_type = factor(rule_type,
                            levels = c("final", 
                                       "proposed"),
                            labels = c("Final Rules", 
                                       "Proposed Rules")))

# set current date
current_date <- format(Sys.Date(), "%B %d, %Y")

# set caption text
caption_text <- paste("Source: Federal Register API;\n excludes corrections to rules.\n\nUpdated:", current_date)

```

```{r generate graph}
line1 <- ggplot(rules_pub_long,
                aes(x = year,
                    y = rule_num,
                    group = rule_type,
                    color = rule_type,
                    linetype = rule_type)) +
  geom_line(aes(linetype = rule_type), linewidth = 1) +
  scale_color_manual(values = c(GWblue, lightblue),
                     guide = "legend") +
  scale_linetype_manual(values = c("solid", "33"),
                        guide = "legend") +
  annotation_custom(l, xmin = -4, xmax = 10, ymin = -450, ymax = -1050) + # for logo (need to play around with these settings)
  coord_cartesian(clip = "off") +
  theme_minimal() +
  theme_RSC +
  theme(
    plot.title = element_text(size = 20, hjust = 0.5, margin = margin(b = 0)),
    legend.position = "top",
    legend.margin = margin(t = 10, b = -50),
    legend.text = element_text(size = 15),
    legend.key.size = unit(2, "lines"),    
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(color = RSCgray, linetype = "solid"),
    panel.grid.minor = element_blank(), 
    plot.caption = element_text(hjust = 1, margin = margin(t = 10, l = 0, unit = "pt")),
    plot.margin = margin(50, 50, 50, 50),
    axis.text.x = element_text(angle = 65, hjust = 1),
    axis.title.y = element_text(size = 15)
  ) +
  xlab(element_blank()) +
  ylab("Number of Rules") +
  ggtitle("Rules Published in the Federal Register by Presidential Year") +
  labs(color = NULL, linetype = NULL, caption = caption_text) +
  scale_y_continuous(
    breaks = seq(0, max(rules_pub_long$rule_num) + 1000, by = 1000),
    expand = c(0, 0), 
    limits = c(0, max(rules_pub_long$rule_num) + 1000)
  )

line1
```

```{r output folder}
# create empty output folder if it doesn't already exist
out = here("output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}
```

```{r save to output}
# save line1 as pdf
ggsave(here("output", "Rules Published in the Federal Register by Presidential Year.pdf"), plot = line1, width = 12, height = 9, dpi = 300)
```

