---
title: "Total Pages Published in the Federal Register"
author: "Henry Hirsch"
date: "2023-11-2"
output: html_document
---

```{r clear environment}
# clear environment
rm(list=ls())
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/tot_pages_pub_in_FR.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "federal_register_pages_by_calendar_year.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```

```{r load packages, results='hide', warning=FALSE}
# load packages
library(tidyverse)
library(png)
library(grid)
library(here)
```

```{r load style, message=FALSE}
# load style
source(here("code", "style.R"))
```

```{r load data}
# load csv using here
tot_pages <- read.csv(here("charts", "data", data_file), skip = 4)

# eventually separate this into another file for reuse, then import/call the function
# ^ HOW TO DO THIS?
get_png <- function(filename) {
  grid::rasterGrob(png::readPNG(filename),interpolate = TRUE)
}

l <- get_png(here("code", "RSC_logo.png"))

```

```{r code}
# current date
current_date <- format(Sys.Date(), "%B %d, %Y")

# create caption text
caption_text <- paste("Source: Federal Register Statistics\n\nUpdated:", current_date)

# get rid of bottom 11 rows
tot_pages <- tot_pages[1:(nrow(tot_pages) - 11), ]

# remove blank first row
tot_pages <- tot_pages[-c(1), ]

# remove all columns except for Year and TOTAL
tot_pages <- tot_pages[, c("Year", "TOTAL")]

# change column names
colnames(tot_pages) <- c("year", "total")

# make total an integer variable (remove commas and then convert)
tot_pages$total <- as.integer(gsub(",", "", tot_pages$total))


```

```{r generate graph}
# generate bar1
bar1 <- ggplot(tot_pages, aes(x = year, y = total)) +
  geom_bar(stat = "identity", fill = GWblue) +
  theme_minimal() +
  theme_RSC +
  ggtitle("Total Pages Published in the Federal Register") +
  ylab("Number of Pages") +
  xlab("") +
  scale_y_continuous(breaks = seq(0, max(tot_pages$total) + 10000, by = 10000), expand = c(0, 0),
                     limits = c(0, max(tot_pages$total) + 10000),
                     labels = function(x) ifelse(x == 0, "0", scales::label_number(suffix = "k", scale = 1e-3)(x))
  ) +
  scale_x_discrete(breaks = seq(min(tot_pages$year), max(tot_pages$year), by = 2)) + 
  labs(caption = caption_text) +
  annotation_custom(l, xmin = -212, xmax = 230, ymin = -19000, ymax = -7000) + # for logo
  coord_cartesian(clip = "off") +
  theme(
    plot.caption = element_text(hjust = 1, margin = margin(t = 0, l = 36, b = 50, unit = "pt")),
    plot.title = element_text(hjust = 0.5, margin = margin(b = 10, unit = "pt")),
    axis.text.x = element_text(angle = 65, hjust = 1, vjust = 1),
    legend.position = "none",
    panel.grid.major.y = element_line(color = RSCgray, linetype = "solid"),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank()
  )

bar1
```

```{r output folder}
# create empty output folder if it doesn't already exist
out = here("output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}
```

```{r save to output}
# save line1 as pdf
ggsave(here("output", "Total Pages Published in the Federal Register.pdf"), plot = bar1, width = 12, height = 9, dpi = 300)
```

