---
title: "Active Actions Published in the Unified Agenda"
author: "Yaxin Zhuang"
date: "`r Sys.Date()`"
output: html_document
---
## Initialize

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location of this file in project directory
library(here)
i_am("charts/code/unified_agenda_active_actions.Rmd")

# import local functions
source(here("charts", "code", "local_utils.R"))
source(here("charts", "code", "style.R"))

# point to dataset
data_file = "active_actions_by_unified_agenda.csv"
"active_actions_by_unified_agenda.csv"

# refresh dataset
copy_dataset(data_file, here("data"), here("charts", "data"))

```



## Load Packages

```{r imports, results='hide', warning=FALSE}

# load packages
library(ggplot2)
library(ggpattern)
library(tidyr)
library(ggrepel)
library(dplyr)
library(scales)
library(cowplot)
library(tidyverse)
library(stringr)
```

## Load data


```{r load_data}

# load csv using here
df1 <- read.csv(here("charts","data", data_file))

```

## Process data


```{r clean_data}

df1_1 <- df1

# name columns and modify data types
colnames(df1_1) <- c("yearseason", "FinalRules", "ProposedRules", "Prerules", "Total")
df1_1$Total <- as.numeric(df1_1$Total)
df1_1$yearseason <- factor(df1_1$yearseason, levels = unique(df1_1$yearseason))

# add rows for missing seasons/UAs, create year, Season, and sort columns [if a yearseason value just specifies the year but not the season (e.g. "2012"), then Fall will be assigned as the season]
df1_1a <- df1_1 %>%
  add_row(yearseason = "1995 Spring",
          FinalRules = 0,
          ProposedRules = 0,
          Prerules = 0,
          Total = 0,
          .before = 1) %>%
  add_row(yearseason = "2012 Spring",
          FinalRules = 0,
          ProposedRules = 0,
          Prerules = 0,
          Total = 0,
          .before = 35) %>%
  mutate(year = as.numeric(substr(yearseason, 1, 4))) %>%
  mutate(season = str_trim(factor(substr(yearseason, 6, 12)))) %>%
  mutate(season2 = case_when(season == "" ~ "Fall", TRUE ~ season)) %>%
  select(-season, Season = season2)

df1_1a$sort <- seq.int(nrow(df1_1a))
df1_1a$Season <- factor(df1_1a$Season, levels = c("Spring", "Fall"))

# use expand.grid to create a complete df with every possible combination of years and seasons, then merge with df1_1a, then set all NA values = to 0
all_years <- unique(df1_1a$year)
all_seasons <- c("Spring", "Fall")
df1_1a_complete <- expand.grid(year = all_years, Season = all_seasons)
df1_1a_complete <- df1_1a_complete %>%
  left_join(df1_1a, by = c("year", "Season")) %>%
  mutate(Total = ifelse(is.na(Total), 0, Total)) %>%
  arrange(year, Season)

```

## Plot data


```{r plot_data, results='markup'}
#annotation
current_date <- format(Sys.Date(), "%B %d, %Y")
caption_text <- paste("Source: Office of Information and Regulatory Affairs \n\nUpdated:", current_date)
wrapped_caption <- paste(strwrap(caption_text, width = 75), collapse = "\n")

bar2 <- ggplot(df1_1a_complete,
        aes(y = Total, x = as.factor(year))) +
  geom_bar(aes(fill = Season), stat = "identity", position = "dodge") +
  scale_fill_manual(values = c(GWbuff, GWblue)) +
  scale_x_discrete(labels = df1_1a$year, breaks = df1_1a$year) +
  ggtitle("Active Actions in the Unified Agenda") +
  ylab("Number of Actions \n") +
  xlab("\nNote: Only the Fall Agenda is available for 1995, and only one Agenda was published in 2012. Active actions refer to rulemakings \nin a pre-rule, proposed rule or final rule stage as indicated by the Unified Agenda.") +
  scale_y_continuous(breaks = seq(0, max(df1_1a$Total)+500, by = 500), expand = c(0, 0),
                     limits = c(-2, max(df1_1a$Total)+500)) +
  coord_cartesian(clip = "off") +
  labs(caption = wrapped_caption)+
  theme_minimal() +
  theme_RSC +
  theme(
      plot.title = element_text(hjust = 0.5, vjust = 0, margin = margin(b = 30), size = 20),
      legend.position = "bottom",
      legend.title = element_blank(),
      legend.text = element_text(size = 12),
      panel.grid.major.x = element_blank(),
      axis.text.x = element_text(angle = 65, hjust = 1, vjust = 1, size = 12),
      axis.title.x = element_text(size = 12, angle = 0, vjust = 0.5, hjust = 0, margin = margin(t = 0)),
      axis.line.x = element_line(linewidth = 1, color = RSCgray),

      #axis.ticks.x = element_line(color = RSCgray),
      axis.text.y = element_text(size = 12),
      axis.title.y = element_text(size = 12, angle = 90, vjust = 0.5, hjust = 0.5, margin = margin(r = 10)),# modified margin to adjust the space between title and y-axis 
      panel.grid.major.y = element_line(color = RSCgray, linetype = "solid", linewidth = 0.50),
      panel.grid.minor = element_blank(),
      plot.caption = element_text(hjust = 1, vjust = 10, margin = margin(t = 10, l = 6, unit = "pt"), size = 11),
      plot.margin = margin(50, 50, 50, 50)
    )

```

```{r}
suppressWarnings({new_bar <- ggdraw() +
      draw_plot(bar2) +
      draw_image(logo, x = 0.125, y = 0.03, halign = 0, valign = 0, width = 0.2)

new_bar})
```


```{r save}
# create empty output folder if it doesn't already exist
out = here("charts", "output")
if (!dir.exists(out)){
  dir.create(out, showWarnings = FALSE)
}

image_name = "active_actions_by_unified_agenda"

ggsave(here("charts", "output", paste0(image_name, ".pdf")), plot = new_bar, width = 12, height = 9, dpi = 300)

ggsave(here("charts", "output", paste0(image_name, ".png")), device = "png", plot = new_bar, width = 1200, height = 900, units = "px", dpi = 96, bg = "white")

```

