name: Run Public Law Data Script

on:
  push:
    branches:
      - '**'  # run on all branches
    paths:
      - 'data/public_laws/**'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r data/public_laws/requirements.txt

      - name: Run Python script
        env:
          API_KEY: ${{ secrets.CONGRESS_API_KEY }}
        run: python data/public_laws/collect_public_law_data.py
