name: Keep Alive

on:
  schedule:
    - cron: '0 7,18 * * *'
  workflow_dispatch:

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Push keep alive commit
        run: |
          git config user.email "bot@github.com"
          git config user.name "streamlit-keep-alive-bot"
          echo "$(date)" > dashboards/monthly_sig_rules/.keep_alive
          git add dashboards/monthly_sig_rules/.keep_alive
          git commit -m "chore: keep dashboards alive"
          git push
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
